accounts/api/urls.py
from django.conf.urls import url


from . import views

urlpatterns = [
    url(
        r"^profile/(?P<pk>\d+)/$",
        views.UserProfileDetailAPIView.as_view(),
        name="userprofile_api",
    ),
    url(
        r"^profile/(?P<pk>\d+)/logs/$",
        views.UserProfileFlightLogsListAPIView.as_view(),
        name="userprofile_logs_api",
    ),
    url(
        r"^profile/(?P<pk>\d+)/uas/$",
        views.UserProfileUASListAPIView.as_view(),
        name="userprofile_logs_api",
    ),
    url(r"^login/$", views.LoginAPIView.as_view(), name="login_api"),
    url(r"^signup/$", views.SignUpAPIView.as_view(), name="signup_api"),
    # url(r"^logs/list/$", views.FlightLogListAPIView.as_view(), name="logs_list_api"),
    # url(r"^logs/test/$", views.FlightLogReserveAirspace.as_view(), name="logs_test"),
    # url(r'^logs/(?P<pk>\d+)/update$' , views.FlightLogUpdateView.as_view(), name='log_update'),
]


accounts/urls.py
from django.conf.urls import url

# from django.contrib.auth.views import login, logout #TODO: Login/logout/signup Use this instead???
from . import views

app_name = "accounts"

urlpatterns = [
    url(r"^login/$", views.LoginView.as_view(), name="login"),
    url(r"^logout/$", views.logout_view, name="logout"),
    url(r"^signup/$", views.SignUp.as_view(), name="signup"),
    url(r"^profile/(?P<pk>[\-\w]+)/update/$", views.edit_user, name="edit_profile"),
    url(r"^profile/(?P<pk>\d+)/$", views.ViewProfile.as_view(), name="view_profile"),
]


maps/urls.py
from django.conf.urls import url

from djgeojson.views import GeoJSONLayerView

from .models import GeofenceLocations,LocationPoints,Obstacles
from . import views

urlpatterns = [
        url(r'^$', views.view_maps, name='view_maps'),

        # url(r'^locations/$', views.locations_datasets, name='locations'),

        url(r'^locations/datasets$', GeoJSONLayerView.as_view(model=LocationPoints,
        properties=('name','radius','ICAO_shortcode','IATA_shortcode',)),
        name='location_datasets'),

        # url(r'^geofence/datasets$', views.geofence_datasets, name='geofence_datasets'),

        url(r'^geofence/datasets$', GeoJSONLayerView.as_view(model=GeofenceLocations,
        properties=('name',)),
        name='geofence_datasets'),

        url(r'^geofences/$', views.view_geofences, name='view_geofences'),

        # url(r'^geofences/view$', views.geofence_datasets, name='geofences'),

        url(r'^geofences/create/$', views.LocationsCreateView.as_view(), name='create_location'),


        url(r'^obstacles/create/$', views.ObstaclesCreateView.as_view(), name='create_obstacles'),

        url(r'^obstacles/datasets$', GeoJSONLayerView.as_view(model=Obstacles,
        properties=('height','type','description','obstacle_type')),
        name='obstacles_datasets'),

]

accounts/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from phonenumber_field.modelfields import PhoneNumberField

# from django.dispatch import receiver

from organizations.models import Organization


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = PhoneNumberField(
        default=models.NOT_PROVIDED, null=True, unique=True, help_text="+254...."
    )
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_pic = models.ImageField(upload_to="images/profile_pic", blank=True)
    organization = models.ForeignKey(
        Organization, blank=True, null=True, on_delete=models.CASCADE
    )

    def __str__(self):
        return str(self.user.username)

    def get_userprofile_pic_url(self):
        return self.profile_pic.url


def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = UserProfile(user=user)
        user_profile.save()


post_save.connect(create_profile, sender=User)

accounts/forms.py
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm, )
from django.contrib.auth.models import User

# from .models import UserProfile
from django import forms


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = User

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['username'].label = 'Display Name'
            self.fields['email'].label = 'Email address'


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

accounts/api/views.py
from rpas.models import Rpas
from django.contrib.auth import (
    login as django_login,
    logout as django_logout,
    authenticate as django_authenticate,
)
from django.contrib.auth.models import User
from rest_framework import generics, permissions, status, serializers, exceptions
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.authtoken.models import Token
from rest_framework.generics import CreateAPIView, RetrieveAPIView


from rest_framework.authentication import TokenAuthentication


from accounts.api.serializers import (
    SignupSerializer,
    UserProfileDetailSerializer,
    UserProfileFlightLogSerializer,
    UserProfileUASListSerializer,
)
from accounts.models import UserProfile

from applications.models import ReserveAirspace
from accounts.api.serializers import LoginSerializer

from django.contrib.auth import get_user_model

User = get_user_model()

from rest_framework import serializers, exceptions


from django.core.exceptions import ValidationError


class UserProfileDetailAPIView(generics.RetrieveAPIView):
    serializer_class = UserProfileDetailSerializer
    lookup_field = "pk"
    queryset = UserProfile.objects.all()


class UserProfileFlightLogsListAPIView(generics.ListAPIView):
    serializer_class = UserProfileFlightLogSerializer

    def get_queryset(self):
        """
        This view should return a list of all the logs
        for the currently authenticated user.
        """

        try:
            url_pk = self.kwargs.get("pk")
            user_from_url = User.objects.get(pk=url_pk)
            if user_from_url == self.request.user:

                queryset = ReserveAirspace.objects.filter(
                    created_by=self.request.user
                ).order_by("-id")

                return queryset
            else:
                return None
        except:
            return None


class UserProfileUASListAPIView(generics.ListAPIView):
    serializer_class = UserProfileUASListSerializer

    def get_queryset(self):
        """
        This view should return a list of all the uas
        for the currently authenticated user.
        """

        try:
            url_pk = self.kwargs.get("pk")
            user_from_url = User.objects.get(pk=url_pk)

            if user_from_url == self.request.user:

                queryset = Rpas.objects.filter(
                    organization=user_from_url.userprofile.organization
                ).order_by("-id")

                return queryset
            else:
                return None
        except:
            return None


class LoginAPIView(APIView):
    permission_classes = (permissions.AllowAny,)
    authentication_classes = (TokenAuthentication,)

    def post(self, request):
        print(request.data, request.data)

        serializer = LoginSerializer(data=request.data)
        # print(serializer, "serializer")
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data["user"]
        # print(user, "user")
        django_login(request, user)
        token, created = Token.objects.get_or_create(user=user)
        # return token.key

        return Response({"token": token.key}, status=200)


class SignUpAPIView(CreateAPIView):
    permission_classes = (permissions.AllowAny,)
    authentication_classes = []
    serializer_class = SignupSerializer

    def post(self, request):
        print(request.data, "this is signup request.data")
        serializer = SignupSerializer(data=request.data)

        # print(serializer,"serializer")

        if serializer.is_valid():
            # try:
            # phone_number = request.data["phone_number"]
            # from accounts.models import SignUpPassword
            # import random

            # rand_password = random.randint(1000, 9999)
            # print("this is the random password")

            # SignUpPassword.objects.create(
            #     unregistered_user=phone_number, password=rand_password
            # )

            # from accounts.sms import send_sms

            # message = (
            #     f"{rand_password} use this code to confirm your MFUKO Registration"
            # )
            # print(message, "should be message ")

            # if not settings.IS_TESTING:
            #     print("pytest is not running")

            #     try:
            #         x = send_sms.SMS().send_sms_sync(phone_number, message)

            #         print(x, "should be sent sms ")
            #     except Exception as e:
            #         print(e, "error in sending confirmation message")
            # else:
            #     print("pytest running, hence we are not running sms client")

            # except:
            #     print("cannot create confirmation password")
            #     return Response(
            #         {
            #             "Response_Code": 1,
            #             "ResultDesc": "Cannot create confirmation password",
            #         },
            #         status=200,
            #     )

            username = request.data["username"]
            print(username, "this should be the create username")

            # first_name = request.data["first_name"]
            # print(first_name, "this should be the create first_name")

            email = request.data["email"]
            print(email, "this should be the create email")

            password = request.data["password"]
            print(password, "this should be the create password")

            try:
                user_obj = User(username=username, email=email)
                user_obj.set_password(password)

                print(user_obj, "this should be the create user_obj")

                user_obj.save()

                new_user = User.objects.get(username=username, email=email)
                django_login(request, new_user)
                token, created = Token.objects.get_or_create(user=new_user)
                # return token.key

                # return Response({"token": token.key}, status=200)
                return Response(
                    {
                        "Response_Code": 0,
                        "ResultDesc": "Initial registration successful",
                        "token": token.key,
                    },
                    status=200,
                )

            except:
                print("cannot create user")
                return Response(
                    {"Response_Code": 2, "ResultDesc": "Cannot create user"}, status=200
                )

        else:
            print("error in signup")
            return Response(data=serializer.errors, status=200)


accounts/views.py
from django.shortcuts import render

from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.forms.models import inlineformset_factory
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from flight_plans.models import FlightLog
from rpas.models import Rpas

from . import (
    forms,
)  # TODO: where is this needed? see line below and resolve to use just one in this doc
from .forms import UserForm
from .models import UserProfile

# Create your views here.


class LoginView(generic.FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy("view_airspace")
    template_name = "accounts/login.html"

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.request, **self.get_form_kwargs())

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect("/account/login")


class SignUp(generic.CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"


@login_required()  # only logged in users should access this
def edit_user(request, pk):
    # querying the User object with pk from url
    user = User.objects.get(pk=pk)

    # prepopulate UserProfileForm with retrieved user values from above.
    user_form = UserForm(instance=user)

    # The sorcery begins from here, see explanation below
    ProfileInlineFormset = inlineformset_factory(
        User,
        UserProfile,
        fields=(
            "phone_number",
            "organization",
            "bio",
            "profile_pic",
            "location",
            "birth_date",
        ),
    )

    formset = ProfileInlineFormset(instance=user)

    if request.user.is_authenticated and request.user.id == user.id:
        if request.method == "POST":
            user_form = UserForm(request.POST, request.FILES, instance=user)
            formset = ProfileInlineFormset(request.POST, request.FILES, instance=user)

            if user_form.is_valid():
                created_user = user_form.save(commit=False)
                formset = ProfileInlineFormset(
                    request.POST, request.FILES, instance=created_user
                )

                if formset.is_valid():
                    created_user.save()
                    formset.save()
                    # return HttpResponseRedirect('/account/profile/')
                    return HttpResponseRedirect(
                        reverse("accounts:view_profile", args=(user.id,))
                    )

        return render(
            request,
            "accounts/edit_profile.html",
            {"noodle": pk, "noodle_form": user_form, "formset": formset},
        )
    else:
        raise PermissionDenied


# class view_profile(generic.TemplateView):
#     template_name = "accounts/profile.html"
#     # model = UserProfile
#
#     def get(self, request):
#         myrpas = Rpas.objects.filter(organization = request.user.userprofile.organization)
#         myflightlogs = FlightLog.objects.filter(user = request.user)
#         args = {'myrpas': myrpas, 'myflightlogs':myflightlogs}
#         return render(request, self.template_name ,args)


class ViewProfile(LoginRequiredMixin, generic.DetailView):
    template_name = "accounts/profile.html"
    model = UserProfile

    def get_context_data(self, *args, **kwargs):
        context = super(ViewProfile, self).get_context_data(**kwargs)
        pk = self.kwargs["pk"]
        thisuser = User.objects.get(pk=pk)
        org = thisuser.userprofile.organization
        context["myrpas"] = Rpas.objects.filter(organization=org)
        context["myflightlogs"] = FlightLog.objects.filter(user=thisuser)
        return context


def error_404(request, exception):
    data = {}
    return render(request, "errors/404.html", data)


def error_500(request):
    data = {}
    return render(request, "errors/500.html", data)

accounts/templates/accounts/edit_profile.html
{% extends "base.html" %}

{% block head %}
    <title>My Profile</title>
{% endblock %}



{% block body %}

<section class="content-header">
      <h5>Hey  <b>{{ user.get_full_name }}</b>,
    <small> Edit Your Profile</small> </h5>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="">My Profile</a></li>
  </ol>
</section>

<section class="content">



  <form method="post"  enctype="multipart/form-data">
  {% csrf_token %}
  {% load bootstrap3 %}

          {{ formset.management_form }}


        {% bootstrap_form_errors noodle_form %}
        {% bootstrap_formset_errors formset %}




              {% for form in formset%}


        {{form.id }}


        <div class="row">

          <div class="col-sm-4">

            <div class="panel panel-default">
              <div class="panel-body">
                <div class="media-center">
                  {% if request.user.userprofile.profile_pic %}
                  <img class="img-responsive" src="{{request.user.userprofile.profile_pic.url}}" alt="Profile Pic Missing!">
                  {% endif%}
                </div>
                <p>{% bootstrap_field form.profile_pic %}</p>
                <hr>
              </div>
          </div>

          </div>
          <p></p>
          <!-- To give spacing to next card in mobile -->

          <div class="col-sm-4">

            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title">Personal Info</h3>
              </div>
              <div class="panel-body">
                <h6 class="card-title">
                  <b>{% bootstrap_field noodle_form.first_name %}
                {% bootstrap_field noodle_form.last_name %}
                {% bootstrap_field noodle_form.email %}
                {% bootstrap_field form.phone_number %}
                </b>
              </h6>
              </div>
          </div>

          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Organization</h3>
            </div>
            <div class="panel-body">
              {% bootstrap_field form.organization %}
              </div>
          </div>

          </div>

      <div class="col-sm-4">

        <div class="panel panel-primary">
          <!-- Default panel contents -->
          <div class="panel-heading">Personal Info</div>
            <div class="panel-body">
              <h6 class="card-title">
                  <b>{% bootstrap_field form.location %}</b>
                  <b>{% bootstrap_field form.birth_date %}</b>
                  <b>{% bootstrap_field form.bio %}</b>
             </h6>
            </div>
        </div>

      </div>


        </div>


<button type="submit" class="btn btn-primary btn-lg btn-block">Save changes</button>


</form>

</div>
<!--  Jumbotron -->
  {%endfor%}


</section>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load static %}

{% block head %}
    <title>Login</title>


   <style type="text/css">

  .lockscreen-wrapper {
    margin-top: 10px;

    }

    .pull-right {
    float: right; 
    }

    .lockscreen-credentials{
      width: 50%;
    }
    </style>


{% endblock %}


{% block body %}


<br>

<body class="hold-transition lockscreen">
<!-- Automatic element centering -->
    <div class="lockscreen-wrapper">
      <div class="lockscreen-logo"  >
        <img src="{% static 'logo/logo.png' %}" class="img-responsive center-block" alt="." style="max-height:60px">
          <b>Login</b>
    </div>

<p><strong>{{ form.non_field_errors }}</strong></p>


  <!-- START LOCK SCREEN ITEM -->
  <div class="lockscreen-item">
 <!-- lockscreen credentials (contains the form) -->


    <form class="lockscreen-credentials"  method="POST">



      <div class="input-group">
        {% csrf_token %}
        {{ form.fieldname.errors }}

        <span>Username: {{form.username}}</span>
        <p></p>
        <span>Password: {{form.password}}</span>
        <p></p>
          <span><button type="submit" class="btn" style="float: right">
            <i class="fa fa-arrow-right text-muted fa-2x"></i></button></span>
            <p></p>
            <span></span>

      </div>

    </form>
  </div>
  <!-- /.lockscreen-item -->


  <div class="text-center">
    <a href="{% url 'accounts:signup' %}"> <b>Or Sign Up here</b></a>
  </div>
  <div class="lockscreen-footer text-center">
    Copyright  <b>ANGA UTM &copy; 2018</b> <a href="" class="text-black"> | Geoffrey Nyaga</a><br>
    All rights reserved
  </div>

</div>

</body>
{% endblock %}



{%block includes%}
{% endblock%}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block head %}

{% if request.user == userprofile.user%}
    <title>My Profile</title>
    {% else %}
    <title>Profile</title>
    {% endif %}
{% endblock %}



{% block body %}


<section class="content-header">

  {% if request.user == userprofile.user%}
      <h5> Hey  <b>{{ userprofile.user.get_full_name }}</b>,
    <small> Welcome To Your Profile!</small> </h5>
  <ol class="breadcrumb">
    <li><a href="{% url 'home' %}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="">My Profile</a></li>
  </ol>
  {% else %}

      <h5>  <b>{{ userprofile.user.get_full_name }}</b> |
    <small> Profile Page</small> </h5>
  <ol class="breadcrumb">
    <li><a href="{% url 'home' %}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><a href="">{{userprofile.user.username}}</a></li>
  </ol>
  {% endif %}
</section>




<section class="content">

    <div class="row">

      <div class="col-sm-4">

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="media-center">
              {% if userprofile.profile_pic %}
              <img class="img-responsive" src="{{userprofile.profile_pic.url}}" alt="Profile Pic Missing!">
              {%else%}
              <img class="img-responsive" src="" alt="Profile Pic Missing!">
              {% endif %}
            </div>
            <hr>
            <h4 class="card-title">{{ userprofile.user.get_full_name }}</h4>
            <h6 class="card-title">Phone No: {{ userprofile.phone_number }}</h6>
            <p class="card-text">Bio: {{ userprofile.bio|linebreaks }}</p>
          </div>

          {% if request.user == userprofile.user%}
          <div class="panel-footer">
            <a class="btn btn-primary" href="{% url 'accounts:edit_profile' pk=user.pk %}"
            role="button"> <i class="fa fa-user-o" aria-hidden="true"></i>
            Edit Profile</a>
        </div>
        {% endif %}
      </div>

      </div>
      <p></p>
      <!-- To give spacing to next card in mobile -->





      <div class="col-sm-4">
        <div class="panel panel-primary">
          <!-- Default panel contents -->
          <div class="panel-heading">My Flight Logs</div>
          <div class="panel-body">
          <small> Includes Flights even as co-pilot</small>
          </div>
          <ul class="list-group">
              <!-- List group -->
          {% for logs in myflightlogs %}

            <li class="list-group-item">
              <span class="badge">Done</span>
              <a href="{% url 'log_detail' pk=logs.pk %}">{{logs}}</a>
            </li>
              {% endfor %}
          </ul>
        </div>

        <div class="panel panel-primary">
          <!-- Default panel contents -->
          <div class="panel-heading">My RPAS</div>
          <div class="panel-body">
            <small> Includes All Rpas by your Organization</small>
          </div>
          <ul class="list-group">
              <!-- List group -->
          {% for rpas in myrpas %}

            <li class="list-group-item">
              <span class="badge">{{rpas.rpas_serial}}</span>
              <a href="{% url 'rpas_detail' pk=rpas.pk %}"> {{rpas}}</a>
            </li>
              {% endfor %}
          </ul>
        </div>

      <div class="list-group">
        <a href="" class="list-group-item active">
          Flights
        </a>
        <a href="#" class="list-group-item">
          <i class="fa fa-clock-o" aria-hidden="true"></i>
          Total Hours: xx
        </a>
        <a href="#" class="list-group-item">
          <i class="fa fa-plane" aria-hidden="true"></i>
          Rated Aircrafts: xx
        </a>
        <a href="#" class="list-group-item">
          <i class="fa fa-certificate" aria-hidden="true"></i>
          Certificates: xx
        </a>
      </div>

</div>


  <div class="col-sm-4">

    <div class="panel panel-primary">
      <!-- Default panel contents -->
      <div class="panel-heading">Info</div>

      <ul class="list-group">
        <li class="list-group-item">
          Username: {{ userprofile.user.username }}
        </li>
        <li class="list-group-item">
          <i class="fa fa-map-marker" aria-hidden="true"></i>
          Location: {{ userprofile.location }}
        </li>
        <li class="list-group-item">
          <i class="fa fa-calendar" aria-hidden="true"></i>
          Birth Date: {{ userprofile.birth_date }}
        </li>

      </ul>
    </div>


    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Organization</h3>
      </div>
      <div class="panel-body">

        <i class="fa fa-building" aria-hidden="true"></i>
        Company: {{ userprofile.organization.organization_details.name }}
<p></p>
        <i class="fa fa-certificate" aria-hidden="true"></i>
        ROC No: {{ userprofile.organization }}</p>
<p></p>
        <i class="fa fa-map-marker" aria-hidden="true"></i>
        Location: {{ userprofile.organization.organization_details.city }}
<p></p>
<a href="{{ userprofile.organization.organization_details.website}}" target="_blank">
        <i class="fa fa-external-link" aria-hidden="true"></i>
        {{ userprofile.organization.organization_details.website}}</a>

      </div>
    </div>

  </div>


    </div>


</section>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block head %}
    <title>Sign Up</title>

{% endblock %}



{% block body %}
<section class="content">

  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Sign Up</h4>
      <form class="" action="" method="POST">
        {% csrf_token %}

          {% bootstrap_form_errors form %}

        <div class="row">
          <div class="col-sm-4">
            <span>{% bootstrap_field form.username %}</span>
          </div>
          <div class="col-sm-2">

          </div>
          <div class="col-sm-3">
            {% bootstrap_field form.email %}
          </div>

        </div>
        <br>
    <div class="row">
      <div class="col-sm-6">
               {% bootstrap_field form.password1 %}
          </div>
          <div class="col-sm-4">
            <!-- {{form.password1}} -->
            {% bootstrap_field form.password2 %}
          </div>

    </div>


           <button type="submit" class="btn btn-primary btn-lg btn-block">Sign Me Up!</button>

      </form>
    </div>

  </div>
</section>
{% endblock %}

{%block includes%}
{% endblock%}