maps/urls.py
from django.conf.urls import url

from djgeojson.views import GeoJSONLayerView

from .models import GeofenceLocations,LocationPoints,Obstacles
from . import views

urlpatterns = [
        url(r'^$', views.view_maps, name='view_maps'),

        # url(r'^locations/$', views.locations_datasets, name='locations'),

        url(r'^locations/datasets$', GeoJSONLayerView.as_view(model=LocationPoints,
        properties=('name','radius','ICAO_shortcode','IATA_shortcode',)),
        name='location_datasets'),

        # url(r'^geofence/datasets$', views.geofence_datasets, name='geofence_datasets'),

        url(r'^geofence/datasets$', GeoJSONLayerView.as_view(model=GeofenceLocations,
        properties=('name',)),
        name='geofence_datasets'),

        url(r'^geofences/$', views.view_geofences, name='view_geofences'),

        # url(r'^geofences/view$', views.geofence_datasets, name='geofences'),

        url(r'^geofences/create/$', views.LocationsCreateView.as_view(), name='create_location'),


        url(r'^obstacles/create/$', views.ObstaclesCreateView.as_view(), name='create_obstacles'),

        url(r'^obstacles/datasets$', GeoJSONLayerView.as_view(model=Obstacles,
        properties=('height','type','description','obstacle_type')),
        name='obstacles_datasets'),

]

notifications/urls.py
from django.conf.urls import url

from . import views

app_name = "notifications"

urlpatterns = [
    url(r"^$", views.NotificationsListView.as_view(), name="notifications_list"),
    url(r"^mark-all$", views.mark_all_notifications_as_read, name="mark_all_as_read"),
    url(
        r"^(?P<pk>\d+)/delete/$",
        views.NotificationDeleteView.as_view(),
        name="notification_delete",
    ),
    url(r"^test$", views.test_notifications, name="test_notification"),
]


notifications/models.py
from django.db import models
from django.contrib.auth.models import User


class Notifications(models.Model):
    class Meta:
        """Meta definition for Notifications."""

        verbose_name = "Notification"
        verbose_name_plural = "Notifications"

    title = models.CharField(max_length=120, blank=True, null=True)
    receiver = models.ForeignKey(
        User, related_name="send_notification_to", on_delete=models.CASCADE
    )

    date_created = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

notifications/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView, DeleteView

from .models import Notifications


class NotificationsListView(ListView):
    context_object_name = "notifications_list"
    template_name = "notifications/notifications_list.html"
    # FIX ME: it seems that the app name in the url is irrevant
    """ FIXED: Its because the default template django asks for is notifications/notifications_list.html
        and that's what I had created, so changing the above to a wrong url will amke django default to default url' \
        which will always be there
    """

    def get_queryset(self):
        return Notifications.objects.filter(receiver=self.request.user).order_by("-id")


# TODO: Notifications DELETEVIEW or ajax/jquery delete and/or mark  all as read?

# TO DO: Notifications is_read
# -- FIXED


def mark_all_notifications_as_read(request):
    all_user_unread_notifications = Notifications.objects.filter(
        receiver=request.user
    ).filter(is_read=False)

    for all_user_unread_notification in all_user_unread_notifications:
        all_user_unread_notification.is_read = True
        all_user_unread_notification.save()

    return HttpResponseRedirect(reverse("notifications:notifications_list"))


class NotificationDeleteView(DeleteView):
    model = Notifications
    success_url = "/notifications/"


def test_notifications(request):
    # The group_name should be the name you would define.
    webpush = {"group": "CAA"}

    return render(
        request, "notifications/a_notification_test.html", {"webpush": webpush}
    )

notifications/templates/notifications/a_notification_test.html

<!DOCTYPE html>

<html lang="en">

   {% load static %} 
   
   {% load webpush_notifications %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title> Notifications</title>
  
  {% webpush_header %}

 <script id="service-worker-js" type="text/javascript" src="{% static 'pwabuilder-sw.js' %}"></script>

</head>

<body>
   {% webpush_button %}
  <p> Hello World! </p>
</body>


</html>

notifications/templates/notifications/notifications_confirm_delete.html

{% extends "base.html" %}

{%load static %} 


{% block head %}

<title> Confirm Delete</title>


{%endblock%}

{%block body%} 

<section class="content-header">
    <h4>
        Confirm Delete
    </h4>

</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-xs-3">

        </div>
        <div class="col-xs-6">
            <form method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete <b>'{{object.title}}'</b>?</p>
                <br>
                <div class='text-center'>
                    <input class="btn btn-danger r" type="submit" value='Delete'>
                </div>
                <hr>
                <a class='btn btn-success btn-block' href="{% url 'notifications:notifications_list' %}"> Go Back Instead</a>
            
            </form>
        </div>
        <div class="col-xs-3">
        
        </div>
    </div>

</section>

{%endblock%}

notifications/templates/notifications/notifications_list.html
{% extends "base.html" %}

{% load static %}


{% block head %}

  <title> Notifications</title>


    <style>
      #unread-timeline-item {
    -webkit-box-shadow: 0 1px 1px rgba(0,0,0,0.1);
    box-shadow: 0 1px 1px rgba(0,0,0,0.1);
    border-radius: 3px;
    margin-top: 0;
    background: #d2d6de;
    color: #444;
    margin-left: 60px;
    margin-right: 15px;
    padding: 0;
    position: relative;
}
    </style>
{%endblock%}

{%block body%}


     

  <!-- TODO: READ ALL button: linked to readallview that changes is_read property of the models -->
    <section class="content-header">
      <h1>
        Notifications
        <small>All</small>
      </h1>
      
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- row -->
      <div class="row">
        <div class="col-md-12">
          <!-- The time line -->
          <ul class="timeline">
            <!-- timeline time label -->
            <li class="time-label">
                  <span class="bg-red">
                   2018 only
                  </span>
                  <span class="pull-right">
                    <a  href="{% url 'notifications:mark_all_as_read' %}" >Mark all As Read</a>
                  </span>
            </li>
           
{% for unread_notification in notifications_list %}
            <li>
              <i class="fa fa-exclamation-triangle bg-red"></i>

              <div class="timeline-item" {% if not unread_notification.is_read %}
                 id=unread-timeline-item
              {% endif %}    >
                

                <!-- <h3 class="timeline-header"><a href="#"> NOTAM ALERT! </a> <small>Urgent action required</small></h3> -->

                <div class="timeline-body">
                {{unread_notification.title}}
                <span class="pull-right">
                  <i class="fa fa-clock-o"></i> {{unread_notification.date_created | timesince }} ago 
                  <a class="btn btn-danger btn-xs" href={% url 'notifications:notification_delete' pk=unread_notification.pk%}>X</a>
                </span>
                  
                  
                </span>
                
                </div>
                <!-- <span class="time">
                  <i class="fa fa-clock-o"></i> {{unread_notification.date_created | timesince }} ago 
                </span> -->
              </div>
            </li>

{% endfor %}

            <li>
              <i class="fa fa-video-camera bg-maroon"></i>

              <div class="timeline-item">
                <span class="time"><i class="fa fa-clock-o"></i> 5 days ago</span>

                <h3 class="timeline-header"><a href="#">Admin</a> shared a video</h3>

                <div class="timeline-body">
                  <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/5etvKO8pb24"
                            frameborder="0" allowfullscreen></iframe>
                  </div>
                </div>
                <div class="timeline-footer">
                  <a href="#" class="btn btn-xs bg-maroon">See comments</a>
                </div>
              </div>
            </li>
            <!-- END timeline item -->
            <li>
              <i class="fa fa-clock-o bg-gray"></i>
            </li>
          </ul>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->


    </section>

{%endblock%}